### ISSUE TITLE
-ignore flag

### ISSUE THREAD

**Issue by paulvollmer** [gtalent/liccor#2]
Add `-ignore` flag to the commandline-interface and append functionallity  
short example:

```
./liccor -ignore /path/to/the/directory
```

or for multiple directories:

```
./liccor -ignore "/path/to" "/some/dirs"
```

**Comment by gtalent** [comment]
Added --src flag in 8ee211f7644d165e8b4a621cfb720cc6d0a15aac, which largely solves the same problem.
