### ISSUE TITLE
source code structure

### ISSUE THREAD

**Issue by paulvollmer** [gtalent/liccor#4]
split the cli and the findLicense, findSrc, correct functions to use it programmatically.  
file structure idea:

- cli.go (switch to https://github.com/codegangsta/cli)
- liccor.go (the library. findLicense, findSrc, correct functions...)
- main.go
- version.go

**Comment by paulvollmer** [comment]
@gtalent i've changed the cli and moved the process into a package. you can find the changes at the develop branch: https://github.com/paulvollmer/liccor/tree/develop

**Comment by gtalent** [comment]
Changes pulled.
