### ISSUE TITLE
default license files

### ISSUE THREAD

**Issue by paulvollmer** [gtalent/liccor#5]
at the moment the default license search is set to the one .liccor file.
if we add some more files as fallback, the tool will work better at different repos/projects...

an array like [".liccor", "LICENSE", "LICENSE.txt"...]

the benefit is to remove one flag call (-license LICENSE) at usage...

**Comment by gtalent** [comment]
LICENSE and LICENSE.txt typically contain the license rather than the license notice at the top of files.
